# Generated by Django 5.2.3 on 2025-07-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinformation', '0003_alter_user_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.IntegerField(),
        ),
    ]
