# Generated by Django 5.2.3 on 2025-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinformation', '0006_alter_user_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
