# Generated by Django 5.2.3 on 2025-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinformation', '0007_alter_user_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.EmailField(max_length=50),
        ),
    ]
