# Generated by Django 5.2.3 on 2025-07-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userinformation', '0012_alter_user_managers_user_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
